#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
# config/packages/easy_admin.yaml
easy_admin:
    entities:
        Product:
            - App\Entity\Product
            form:
                fields:
                    - { property: 'illustration', type: 'file' }
            # ...
